services:
  - type: web
    name: clasificador-consultas-estudiantiles
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --browser.gatherUsageStats=false
    autoDeploy: true
